export const weatherTranslations: { [key: string]: string } = {
  "clear sky": "Açık Hava",
  "few clouds": "Az Bulutlu",
  "scattered clouds": "Parçalı Bulutlu",
  "broken clouds": "Çok Bulutlu",
  "overcast clouds": "Kapalı",
  "light rain": "Hafif Yağmurlu",
  "moderate rain": "Orta Şiddetli Yağmurlu",
  "heavy rain": "Şiddetli Yağmurlu",
  "light intensity drizzle": "Hafif Çisenti",
  drizzle: "Çisenti",
  "heavy intensity drizzle": "Yoğun Çisenti",
  thunderstorm: "Gök Gürültülü Fırtına",
  "thunderstorm with light rain": "Hafif Yağmurlu Gök Gürültülü Fırtına",
  "thunderstorm with rain": "Yağmurlu Gök Gürültülü Fırtına",
  "thunderstorm with heavy rain": "Şiddetli Yağmurlu Gök Gürültülü Fırtına",
  "light snow": "Hafif Kar Yağışlı",
  snow: "Kar Yağışlı",
  "heavy snow": "Yoğun Kar Yağışlı",
  sleet: "Karla Karışık Yağmur",
  mist: "Puslu",
  fog: "Sisli",
  haze: "Hafif Sisli",
  smoke: "Dumanlı",
  "sand/dust whirls": "Kum/Toz Fırtınası",
  squalls: "Fırtına",
  tornado: "Hortum",
  "volcanic ash": "Volkanik Kül",
  "light intensity shower rain": "Hafif Sağanak Yağış",
  "shower rain": "Sağanak Yağış",
  "heavy intensity shower rain": "Şiddetli Sağanak Yağış",
  "freezing rain": "Dondurucu Yağmur",
  "light intensity shower snow": "Hafif Sağanak Kar",
  "shower snow": "Sağanak Kar",
  "heavy shower snow": "Yoğun Sağanak Kar"
};
